version: '3'

services:
  chat-microservice:
    image: backend-chat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - chat_network

volumes:
  db-data:

networks:
  chat_network:
    external:
      name: custom_network2
